os:
  - linux
  - windows
language: node_js
node_js:
  - '14'
  - '12'
  - '10'
  - '8'
jobs:
  include:
    - node_js: '14'
      script: npm test
    - node_js: '12'
      script: npm test
    - node_js: '10'
      script: npm test
    - node_js: '8'
      script: npm run test:nolint
